### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Myosotis6535** [InJeCTrL/QQIPShow#1]
could you give me more direction for use?
i can't use it

**Comment by InJeCTrL** [comment]
Hey, thank you for supporting this project, I haven't checked this repo for about 3 years. I will check the logic of code and think if this software is still enable now. Then we will sync in this session.

________________________________
From: Myosotis6535 ***@***.***>
Sent: Saturday, August 12, 2023, 15:21
To: InJeCTrL/QQIPShow ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [InJeCTrL/QQIPShow] help (Issue #1)


could you give me more direction for use?
i can't use it

―

**Comment by InJeCTrL** [comment]
Hi, after diving into this project again, I found this method inside the code logic is not available for current QQ / TIM, since Tencent has updated message connection and transmission path. Sorry to inform you that this project is no longer valid, and I will archive it soon.

Thank you for understanding!
